# DO NOT MODIFY -- auto-generated by Apache Cordova
source 'https://cdn.cocoapods.org/'
platform :ios, '12.0'
use_frameworks!
target 'Bichos Memory' do
	project 'Bichos Memory.xcodeproj'
	pod 'Google-Mobile-Ads-SDK', '~> 8.13.0'
	pod 'GoogleUserMessagingPlatform', '~> 2.0.0'
end
